export const generateRandomName = (gender: string) : string => {
  const femaleNames = [
    'Anna',
    'Maria',
    'Katarzyna',
    'Małgorzata',
    'Agnieszka',
    'Barbara',
    'Krystyna',
    'Ewa',
    'Elżbieta',
    'Zofia',
    'Teresa',
    'Magdalena',
    'Joanna',
    'Janina',
    'Monika',
    'Danuta',
    'Jadwiga',
    'Aleksandra',
    'Halina',
    'Irena',
    'Beata',
    'Marta',
    'Dorota',
    'Helena',
    'Karolina',
    'Grażyna',
    'Jolanta',
    'Iwona',
    'Marianna',
    'Natalia',
    'Patrycja',
    'Izabela',
    'Ewelina',
    'Julia',
    'Wanda',
    'Marzena',
    'Wiesława',
    'Weronika',
    'Wiktoria',
    'Klaudia',
    'Edyta',
    'Emilia',
    'Genowefa',
    'Dominika',
    'Kazimiera',
    'Hanna',
    'Kamila',
    'Martyna',
    'Kinga',
    'Lucyna',
    'Stefania',
    'Józefa',
    'Alina',
    'Zuzanna',
    'Gabriela',
    'Władysława',
    'Mariola',
    'Lidia',
    'Mirosława',
    'Henryka',
    'Wioletta',
    'Czesława',
    'Oliwia',
    'Regina',
    'Bogumiła',
    'Angelika',
    'Sabina',
    'Daria',
    'Aniela',
    'Bogusława'
  ];
  const maleNames = [
    'Piotr',
    'Krzysztof',
    'Andrzej',
    'Jan',
    'Stanisław',
    'Tomasz',
    'Paweł',
    'Marcin',
    'Michał',
    'Marek',
    'Grzegorz',
    'Józef',
    'Łukasz',
    'Adam',
    'Zbigniew',
    'Jerzy',
    'Tadeusz',
    'Mateusz',
    'Dariusz',
    'Mariusz',
    'Wojciech',
    'Ryszard',
    'Jakub',
    'Henryk',
    'Robert',
    'Rafał',
    'Kazimierz',
    'Jacek',
    'Maciej',
    'Kamil',
    'Przemysław',
    'Sebastian',
    'Daniel',
    'Władysław',
    'Zdzisław',
    'Patryk',
    'Bartosz',
    'Edward',
    'Mieczysław',
    'Leszek',
    'Karol',
    'Arkadiusz',
    'Czesław',
    'Waldemar',
    'Szymon',
    'Adrian',
    'Kacper',
    'Bogdan',
    'Eugeniusz',
    'Bartłomiej',
    'Antoni',
    'Franciszek',
    'Stefan',
    'Radosław',
    'Zygmunt',
    'Dominik',
    'Krystian',
    'Konrad',
    'Aleksander',
    'Bogusław',
    'Ireneusz',
    'Włodzimierz',
    'Zenon',
    'Witold',
    'Sylwester',
    'Hubert',
    'Mikołaj',
    'Filip',
    'Wiktor',
    'Bronisław'
  ];
  const spread = (gender === 'Female') ?  femaleNames.length - 1 : maleNames.length - 1;
  const index = Math.floor(Math.random() * spread);

  if (gender.toLowerCase().trim() === 'female') {
    return femaleNames[index];
  } else {
    return maleNames[index];
  }
};

export const getGender = () => {
  const gender = ['male', 'female'];
  const index = Math.floor(Math.random() * 2);
  return gender[index];
};

export default generateRandomName;
